# Generated by Django 2.2.10 on 2021-04-20 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(default='', max_length=10)),
                ('marketindex', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('business', models.CharField(max_length=200)),
                ('detail', models.CharField(default='', max_length=300)),
                ('discuss_url', models.URLField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MyStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invst_type', models.PositiveSmallIntegerField(choices=[(1, 'Domestic'), (2, 'Overseas'), (3, 'Coin')])),
                ('icode', models.CharField(blank=True, max_length=10)),
                ('iname', models.CharField(blank=True, max_length=20, null=True)),
                ('iunitbuyprice', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('iunitcurprice', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, null=True)),
                ('iquantity', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('kcurrencyrate', models.DecimalField(decimal_places=1, default=1, max_digits=8, null=True)),
                ('kbuyprice', models.DecimalField(decimal_places=8, max_digits=18, null=True)),
                ('kcurprice', models.DecimalField(decimal_places=8, default=0.0, max_digits=18, null=True)),
                ('kprofitratio', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, null=True)),
                ('ktotalbuyprice', models.DecimalField(decimal_places=0, default=0.0, max_digits=12, null=True)),
                ('ktotalcurprice', models.DecimalField(decimal_places=0, default=0.0, max_digits=12, null=True)),
                ('ktotalprevbuyprice', models.DecimalField(decimal_places=0, default=0.0, max_digits=12, null=True)),
                ('ktotalprevprice', models.DecimalField(decimal_places=0, default=0.0, max_digits=12, null=True)),
                ('kprofitpreratio', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, null=True)),
                ('kforeverholdyn', models.BooleanField(default=False)),
                ('iupdatedate', models.DateTimeField(auto_now_add=True, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('business', models.CharField(max_length=200, null=True)),
                ('detail', models.CharField(max_length=300, null=True)),
                ('discuss_url', models.URLField(max_length=250, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateField(null=True)),
                ('bamount', models.DecimalField(decimal_places=0, max_digits=12, null=True)),
                ('bincreased', models.DecimalField(decimal_places=0, max_digits=12, null=True)),
                ('bincreasedratio', models.DecimalField(decimal_places=1, default=0.0, max_digits=10, null=True)),
                ('bauthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
